### ISSUE TITLE
Handle multi-line var assignments

### ISSUE THREAD

**Issue by johngibb** [adrianlee44/atom-aligner#12]
Given input like this:

    var Apple = require('apple'),
        Banana = require('banana'),
        Grapefruit = require('grapefruit');

The first item isn't properly lined up, like so:

    var Apple = require('apple'),
        Banana     = require('banana'),
        Grapefruit = require('grapefruit');

I would expect this:

    var Apple      = require('apple'),
        Banana     = require('banana'),
        Grapefruit = require('grapefruit');

**Comment by adrianlee44** [comment]
You can now select and align multiple lines with different indentations which you can now align

```
var Apple = require('apple'),
    Banana     = require('banana'),
    Grapefruit = require('grapefruit');
```

by selecting all three lines and then activate aligner.

```
var Apple      = require('apple'),
    Banana     = require('banana'),
    Grapefruit = require('grapefruit');
```
