### ISSUE TITLE
CSS/SCSS Support

### ISSUE THREAD

**Issue by davelandry** [adrianlee44/atom-aligner#13]

**Comment by mathieucivel** [comment]
+1

**Comment by davelandry** [comment]
+1

**Comment by adrianlee44** [comment]
Looking into this. The current approach I have is to create a separate package with `css/scss` support similar to how `linter` does it

**Comment by davelandry** [comment]
Why make a separate package instead of just including it within this? You already support multiple languages.

**Comment by adrianlee44** [comment]
Vertical align relies on Atom's language parser to align operators and as the package adds support more languages, more configurations are needed for each operator. Some languages label similar operator differently and this might unintentionally align the wrong operator in different languages.

Splitting out language packages will make the configurations easier to maintain and reduce the chance of aligning the wrong operator.

**Comment by davelandry** [comment]
:+1:

**Comment by adrianlee44** [comment]
@davelandry, @mathieucivel 

Vertical-align has been renamed to [aligner](https://atom.io/packages/aligner) and bumped to v0.9.0 with add-on support.

For CSS, SASS, and SCSS support, you can download [aligner-css](https://atom.io/packages/aligner-css).

Let me know if you find any bugs.

**Comment by mathieucivel** [comment]
Thanks :thumbsup:

**Comment by adrianlee44** [comment]
Unfortunately there was a bug with `aligner-css` and it wasn't handling `scss` and `sass`  correctly. I moved support for `scss` and `sass` to its own package [aligner-scss](https://github.com/adrianlee44/atom-aligner-scss) and changed `aligner-css` to support `css` and `less`

**Comment by davelandry** [comment]
Thanks for the update, great stuff! :beers:
