### ISSUE TITLE
Doesn't support ruby 1.9 hashes + CSS?

### ISSUE THREAD

**Issue by MadRabbit** [adrianlee44/atom-aligner#16]
Hey guys, firstly, thank you for an awesome plugin! Secondly, thought I'll report an issue.

Apparently it doesn't work in ruby 1.9 syntax hashes. Which is a bit of a bummer. Try something like this

```ruby
stuff = {
  oh: 1,
  noooo: 2
}
```

Shouldn't be too hard to support, i mean, it's practically the same as the javascript hashes.

Also, a feature request, can you make CSS/LESS work as well?

Thanks!

**Comment by adrianlee44** [comment]
I have added support for CSS and LESS in [aligner-css](https://github.com/adrianlee44/atom-aligner-css). You can find the package on Atom package manager.

**Comment by adrianlee44** [comment]
As for the Ruby syntax, ruby grammar in `language-ruby` needs to be updated first to represent `:` correctly.

I have opened a PR, atom/language-ruby#87 to address this issue. Once that's merged, I'll update [aligner-ruby](https://github.com/adrianlee44/atom-aligner-ruby)

**Comment by MadRabbit** [comment]
Ah sweet! Thank you for the fix and a quick update! Looking forward for the ruby update!

**Comment by lee-dohm** [comment]
As I commented directly on the pull request, this would break expectations for at least some people's syntax themes, mine included. If you wish to customize the colorization of the colon to be different than the rest of the symbol declaration, you can always add something like this to your `styles.less`:

```less
.punctuation.definition.constant.ruby {
  color: red;
}
```

Now, this will change the colorization of *all* colons in symbol declarations. If you wanted to be able to colorize colons in hash key symbol declarations separately from all other symbol declarations, then I would support adding to the current scope definition in language-ruby with something like this:

```
{
  'captures':
    '1':
      'name': 'punctuation.definition.constant.hashkey.ruby'
```

So that you could differentiate it from other symbol declarations.

**Comment by adrianlee44** [comment]
@lee-dohm, the original intension was to distinguish the colon between `:foo` and `foo:` so the package can align the colon accordingly. I think the second suggestion of adding `hashkey` to the scope will do.

Will open another PR on language-ruby to address this issue.

**Comment by lee-dohm** [comment]
:+1:

**Comment by adrianlee44** [comment]
@lee-dohm, just to clarify. Do you mean adding `hashkey` to both 1.5 and 1.6 syntax scope? 

Since I'm trying to distinguish the colon between `:foo` and `foo:`, adding `hashkey` to both syntax scopes won't be useful to me. I was wondering if you have any suggestions.

Thanks for your help! :)

**Comment by lee-dohm** [comment]
I'm suggesting adding `hashkey` to only the Ruby 1.9+ hash syntax scope, the one that allows the colon after the symbol name. And it should be added *only* in the case of the colon appearing after the symbol name.

**Comment by adrianlee44** [comment]
Opened atom/language-ruby#88 to address this issue

**Comment by adrianlee44** [comment]
@MadRabbit, 1.9 syntax hashes should work now with `aligner-ruby` v1.2.0 and Atom v0.190.0.

**Comment by MadRabbit** [comment]
em, i'm afraid i don't see the `aligner-ruby` in the list of available packages

**Comment by adrianlee44** [comment]
@MadRabbit Have you updated Atom to v0.190.0?

**Comment by MadRabbit** [comment]
yup

**Comment by adrianlee44** [comment]
hm... I'm not sure why it's not showing up for you. I'm on Atom v0.190.0 and was able to find `aligner-ruby` v0.12.0. Maybe try restarting Atom, uninstall existing `aligner-ruby` and reinstall it?

**Comment by MadRabbit** [comment]
well that's the thing, i don't have it installed, and I don't see it on the list of available packages either

**Comment by adrianlee44** [comment]
I have reverted Atom requirement and bumped the version to v1.2.1. Let me know if you see the package at all.

**Comment by MadRabbit** [comment]
ah, all working now! sorry, don't know what was the problem, but now i see the `aligner-ruby` and works perfectly!

much appreciated!
