### ISSUE TITLE
Soft tab spaces are replaced with a `·` character

### ISSUE THREAD

**Issue by adrianlee44** [adrianlee44/atom-aligner#17]
From @dcalhoun:
I'm experiencing this issue as well inside of a JavaScript file. My soft tab spaces are replaced with a `·` character. Does atom-aligner take into account whether the user utilizes soft tabs? [Here's a short screencast of the issue](http://quick.as/b7wyfrolo).

![atom-aligner spaces](https://cloud.githubusercontent.com/assets/438664/6924068/71028d32-d79b-11e4-8d57-7e5f67bc95a2.gif)

#### Environment:
- atom-aligner v0.9.1
- atom 0.188.0
- Mac OS X 10.10.2

**Comment by vinnymac** [comment]
Just confirming that I have this issue on Ubuntu 14.04. It appears to happen in all sorts of files, js, coffee, json etc. I have turned off invisibles and it does remedy aligning. Thanks for making a ticket for it.

**Comment by adrianlee44** [comment]
@vinnymac, @dcalhoun: This should be fixed with v0.10.0. Thanks.
