### ISSUE TITLE
Sass/SCSS, alignment only works in Bracket context

### ISSUE THREAD

**Issue by olafgleba** [adrianlee44/atom-aligner#21]
Hi,

atom-aligner + atom-aligner-scss installed. I am not sure which package causes following behaviour:

**Works**:

    .foo {
      // Class context, alignment works well with any <key|property> combination

      $table-padding:      $base-spacing-unit !default;
      $table-border-width: $base-font-size !default;
    }

**Fails**:
     
    // No context (e.g. declaring variables in a configuration.scss file)
    
    $table-padding: $base-spacing-unit !default;
    $table-border-width: $base-font-size !default;

Am i doing something stupid or is it intended behaviour? Thx for your answer.

**Comment by adrianlee44** [comment]
This has to do with `language-sass` not parsing the second case correctly. I'll make a PR with `atom/language-sass`

**Comment by olafgleba** [comment]
Thanks for your effort. And for making this package.

**Comment by adrianlee44** [comment]
Created atom/language-sass#72. Will update `aligner-scss` when the PR is merged.

**Comment by adrianlee44** [comment]
With that latest `Atom` v1.0.3 update, it comes with `language-sass` v0.40.0 which fixes `:`.

Updating `Atom` to v1.0.3 and `aligner-sass` to v1.0.2 should fix this.
