### ISSUE TITLE
Cannot align across multilines with comment

### ISSUE THREAD

**Issue by seoker** [adrianlee44/atom-aligner#22]
Hello,

Thanks for the awesome work, it's very useful for me to beautify codes.
I would like to suggest an enhancement if possible. If I have few lines like
```javascript
var something = {
  // URL parameter missing
  UrlParameterMissing: 0x10000000,
  UserIdMissing: 0x10000001,
  CarIdMissing: 0x10000002,
  // Body parameter missing
  BodyParameterMissing: 0x11000000,
  MobileMissing: 0x11000001,
  OtpMissing: 0x11000002,
  EmailMissing: 0x11000003,
  BirthdayMissing: 0x11000004,
  // Bad format
  BadMobileFormat: 0x12000001,
  BadOtpFormat: 0x12000002,
  BadEmailFormat: 0x12000003,
  BadBirthdayFormat: 0x12000004
}
```
The aligner seems couldn't work while I select line from the first comment (even the first property) to the last properties since some of the selected lines doesn't contain a colon symbol.

What I expect is:
```javascript
var something = {
  // URL parameter missing
  UrlParameterMissing:  0x10000000,
  UserIdMissing:        0x10000001,
  CarIdMissing:         0x10000002,
  // Body parameter missing
  BodyParameterMissing: 0x11000000,
  MobileMissing:        0x11000001,
  OtpMissing:           0x11000002,
  EmailMissing:         0x11000003,
  BirthdayMissing:      0x11000004,
  // Bad format
  BadMobileFormat:      0x12000001,
  BadOtpFormat:         0x12000002,
  BadEmailFormat:       0x12000003,
  BadBirthdayFormat:    0x12000004,
}
```

I'm wondering if this could be enhanced in the future? Thanks!

**Comment by adrianlee44** [comment]
You should be able to set multiple cursors and align each block accordingly. This is still not exactly what you describe though. It's definitely something I can add to aligner. Let me take a look at this.

**Comment by adrianlee44** [comment]
A new option has been added, `Align across comments`, in v0.14.0 which would allow you to do what you describe above.

**Comment by seoker** [comment]
Great, thanks for the effort :)
