### ISSUE TITLE
Aligner doesn't work in some cases with multi-block across comments

### ISSUE THREAD

**Issue by seoker** [adrianlee44/atom-aligner#24]
Hi, I had tried 0.15.0, here I still found some issues.
I'm not sure if there're same issue.

**case 1** (not aligned yet)
```javascript
    // comment 1
    x: 1,
    yyyy: 2,
    zz:3,
    
    // comment 2
    aaa: 4,
    bbbbbbbb:5,
    ccccc:6,
    
    // comment 3
    ddddd: 7,
    e:8,
    ff:9,
```
As you can see, there're 3 blocks, the aligner works if I align each block separately, but:
a. If I select from first line to the last line and press ctrl-cmd-/, only last block get aligned.
b. If I select from last line to the first line and press ctrl-cmd-/, nothing get aligned.

**case 2** (already aligned)
```javascript
    ggg:      0,
    g:        1,
    
    // comment 1
    x:        1,
    yyyy:     2,
    zz:       3,
    
    // comment 2
    aaa:      4,
    bbbbbbbb: 5,
    ccccc:    6,
    
    // comment 3
    ddddd:    7,
    e:        8,
    ff:       9,
```
In this case, the last block will be aligned itself.
That is, if I select from first line to the last line, I get:
```javascript
    ggg:      0,
    g:        1,
    
    // comment 1
    x:        1,
    yyyy:     2,
    zz:       3,
    
    // comment 2
    aaa:      4,
    bbbbbbbb: 5,
    ccccc:    6,
    
    // comment 3
    ddddd: 7,
    e:     8,
    ff:    9,
```
Conversely, if I start select from the last line, I get:
```javascript
    ggg: 0,
    g:   1,
    
    // comment 1
    x:        1,
    yyyy:     2,
    zz:       3,
    
    // comment 2
    aaa:      4,
    bbbbbbbb: 5,
    ccccc:    6,
    
    // comment 3
    ddddd:    7,
    e:        8,
    ff:       9,
```

Here are my environment:
MAC OS X: 10.10.4
Atom: 1.0.7

**Comment by adrianlee44** [comment]
Thanks for reporting this.

It was by design that if there are new lines between each code block + comment, each block will be treated as its separate block and only align the within.

Based on the examples and instructions you have given me, I'm unable to reproduce what you have described. I will continue to look into this issue.

By design, this is what aligner should do:

**case 1**
```javascript
    // comment 1
    x: 1,
    yyyy: 2,
    zz:3,

    // comment 2
    aaa: 4,
    bbbbbbbb:5,
    ccccc:6,

    // comment 3
    ddddd: 7,
    e:8,
    ff:9
```
to
```javascript
    // comment 1
    x:    1,
    yyyy: 2,
    zz:   3,

    // comment 2
    aaa:      4,
    bbbbbbbb: 5,
    ccccc:    6,

    // comment 3
    ddddd: 7,
    e:     8,
    ff:    9
```

**case 2**
```javascript
    ggg:      0,
    g:        1,

    // comment 1
    x:        1,
    yyyy:     2,
    zz:       3,

    // comment 2
    aaa:      4,
    bbbbbbbb: 5,
    ccccc:    6,

    // comment 3
    ddddd:    7,
    e:        8,
    ff:       9,
```
to
```javascript
    ggg: 0,
    g:   1,

    // comment 1
    x:    1,
    yyyy: 2,
    zz:   3,

    // comment 2
    aaa:      4,
    bbbbbbbb: 5,
    ccccc:    6,

    // comment 3
    ddddd: 7,
    e:     8,
    ff:    9,
```

**Comment by seoker** [comment]
Sorry that I had a mistake on the example of case 2, I've edited my post, please check it again.

About the design, I'm just thinking if we could have an option that allow me to align multiple blocks to a single vertical line rather than separate alignment if I select them all at once.
That is, if I really want them align respectively, I would align them one by one. But I'm not sure if it's a convention that a large block of definitions are aligned to a single vertical line, how do you think?

**Comment by adrianlee44** [comment]
@seoker, I just updated aligner to `v0.16.0` with more support for selection blocks.

In order to align the block you described above properly, you can now select the blocks you want to align with the same offset and then call aligner. Let me know if it works.
