### ISSUE TITLE
Python support?

### ISSUE THREAD

**Issue by Zone22** [adrianlee44/atom-aligner#26]
Would you consider adding support for Python?

**Comment by adrianlee44** [comment]
Will definitely like to add support for Python.

May I ask what are some common characters/operators you align in Python?

**Comment by Zone22** [comment]
Here's a [file](https://github.com/Zone22/caster/blob/master/caster/apps/atom.py) that I would be using it on. The characters that I most likely would align would be 'C','R','T' and 'K'.

**Comment by adrianlee44** [comment]
Just published [aligner-python](https://atom.io/packages/aligner-python). Please let me know if it covers all your use cases.
