### ISSUE TITLE
First line unnecessary tabulations

### ISSUE THREAD

**Issue by itadakimas** [adrianlee44/atom-aligner#32]
Hi !

I just noticed that when the alignment is done, the first one is not aligned with the others.

![capture d ecran 2015-09-22 a 14 49 08](https://cloud.githubusercontent.com/assets/688408/10018738/6929bf5e-6139-11e5-8bce-32dcf7eaa532.png)

This is not a JavaScript specific issue.

I don't recall having this problem last month.

**Comment by adrianlee44** [comment]
Thanks for reporting this. Will take a look.

**Comment by adrianlee44** [comment]
The bug should be fixed with v0.16.2. Please let me know if you are still seeing this problem.

**Comment by itadakimas** [comment]
Awesome man thanks !
