### ISSUE TITLE
Aligning React Props

### ISSUE THREAD

**Issue by simonlast** [adrianlee44/atom-aligner#38]
This used to work, but it recently broke for some reason:

Before:

```
<TableRow
    store = {store}
    columns = {columns} />
```

After:

```
<TableRow
    store   = {store}
    columns = {columns} />
```

**Comment by adrianlee44** [comment]
Thanks for reporting this @simonlast.

I'm not sure if this used to work since there hasn't been many changes to `language-html` recently. Let me send in a PR to `language-html` so aligner can align this correctly.

**Comment by adrianlee44** [comment]
Is this code in a jsx file?

**Comment by ambethia** [comment]
Any movement on this? I'm happy to look into it. @adrianlee44 Yes, in JSX files.

**Comment by adrianlee44** [comment]
@ambethia which language package are you using for jsx?

**Comment by ambethia** [comment]
@adrianlee44 https://atom.io/packages/react

**Comment by adrianlee44** [comment]
I'm not sure if there is another package that would work with atom-aligner but the issue with `react` package is that it doesn't parse the `=` character.

Based on this line, https://github.com/orktes/atom-react/blob/master/grammars/JavaScript%20(JSX).cson#L47, you can see that it includes 4 patterns, the attribute name, double quote, single quote and code.

None of these patterns include the `=` character and parse it into an `assignment` token.
