### ISSUE TITLE
Alignment issue with Babel ES6 Javascript

### ISSUE THREAD

**Issue by radnor** [adrianlee44/atom-aligner#41]
How can I make it so that aligner treats the Babel ES6 Javascript language from [language-babel](https://github.com/gandm/language-babel) correctly?

Here's my original object.
```javascript
var initialState = {
  a: [],
  bbb: null,
  ccccc: null,
  ddd: 11,
  eeeeeeee: [],
  fff: 0,
  gggg: {},
  hhh: null,
  iiii: null
};
```

If I'm set to `Babel ES6 JavaScript` from language-babel I get this alignment.
```javascript
var initialState = {
  a: []       , 
  bbb: null   , 
  ccccc: null , 
  ddd: 11     , 
  eeeeeeee: [], 
  fff: 0      , 
  gggg: {}    , 
  hhh: null   , 
  iiii: null
};
```

If I set the language to `JavaScript` I get this (proper) alignment.
```javascript
var initialState = {
  a:        [],
  bbb:      null,
  ccccc:    null,
  ddd:      11,
  eeeeeeee: [],
  fff:      0,
  gggg:     {},
  hhh:      null,
  iiii:     null
};
```

**Comment by adrianlee44** [comment]
So the bug has to do with the language grammar. In language-javascript, `:` has an `operator` scope which allows aligner to determine how to align these characters.

If you can get me the scope of `:` in `language-bable`, that would be great!

**Comment by radnor** [comment]
According to [Babel Language.json](https://github.com/gandm/language-babel/blob/master/grammars/Babel%20Language.json) this is how `:` is treated. Hope this helps! :smile: 

``` json
{
  "comment": "ternary operator - make sure end : is consumed to avoid mistake as flow type",
  "begin": "\\s*(\\?)",
  "end": "\\s*(:)",
  "beginCaptures": {
    "1": { "name": "keyword.operator.ternary.js" }
  },
  "endCaptures": {
    "1": { "name": "keyword.operator.ternary.js" }
  },
  "patterns": [
    { "include": "#expression" }
  ]
}
```

**Comment by adrianlee44** [comment]
There seems to be multiple definitions for `:` depending on the type of the value but they are all `separator.key-value`.

I have updated aligner but there are some testing issues at the moment. I'll be releasing the new version once those are resolved.
