### ISSUE TITLE
Live Preview Mode

### ISSUE THREAD

**Issue by eevmanu** [adrianlee44/atom-aligner#43]
Excellent work, thanks for your package. 
As a suggestion could be very useful to have a live preview with any symbol and apply only to highlighted lines, similar like AlignTab packages in ST (https://github.com/randy3k/AlignTab#live-preview-mode)

**Comment by adrianlee44** [comment]
Thanks for using it and your suggestion. It's an interesting suggestion and I would need to think it through first.
