### ISSUE TITLE
allow for aligning comments

### ISSUE THREAD

**Issue by btkostner** [adrianlee44/atom-aligner#45]
Well done on the package, but there is one thing that seems missing. Being able to align comments together similarly to how variables are aligned.

From this:
```javascript
var Apple      = require('apple'), // this is an apple
    Banana     = require('banana'), // this is a banana
    Grapefruit = require('grapefruit'); // grapefruit is best fruit
```

to something like this:
```javascript
var Apple      = require('apple'),      // this is an apple
    Banana     = require('banana'),     // this is a banana
    Grapefruit = require('grapefruit'); // grapefruit is best fruit
```

**Comment by adrianlee44** [comment]
Thanks for the suggestion. Will look into this.

**Comment by 1vasari** [comment]
I would really like this feature :+1:

**Comment by adrianlee44** [comment]
This is on my roadmap but haven't started working on it yet.

**Comment by adrianlee44** [comment]
Please update to `v0.19.0` for this feature
