### ISSUE TITLE
indent spaces instead of tabs

### ISSUE THREAD

**Issue by geminorum** [adrianlee44/atom-aligner#46]
not following the editor settings to use soft or hard tabs.

> **Tab Type**
> Determine character inserted when Tab key is pressed. Possible values: "auto", "soft" and "hard". When set to "soft" or "hard", soft tabs (spaces) or hard tabs (tab characters) are used. When set to "auto", the editor auto-detects the tab type based on the contents of the buffer (it uses the first leading whitespace on a non-comment line), or uses the value of the Soft Tabs config setting if auto-detection fails.

in my case aligner will convert all indent tabs into spaces

**Comment by adrianlee44** [comment]
Thanks for reporting this @geminorum. Let me take a look.

**Comment by adrianlee44** [comment]
Are you referring to the spaces/tabs before the first character of the line or the spaces/tabs around the character that you are trying to align?

**Comment by geminorum** [comment]
> Are you referring to the spaces/tabs before the first character of the line or the spaces/tabs around the character that you are trying to align?

yes

**Comment by geminorum** [comment]
> Are you referring to the spaces/tabs before the first character of the line or the spaces/tabs around the character that you are trying to align?

before the first character

**Comment by adrianlee44** [comment]
I'm having trouble reproduce the bug. These are the test cases I have tried and please let me know if I miss your use case.

1. Tab Type: auto, Soft Tabs: true
2. Tab Type: soft, Soft Tabs: true
3. Tab Type: hard, Soft Tabs: true
4. Tab Type: auto, Soft Tabs: false
5. Tab Type: soft, Soft Tabs: false
6. Tab Type: hard, Soft Tabs: false

All of the above test cases kept the same indentation length and type when aligning.

I'm on Atom 1.4.0 with aligner 0.17.4.

Can you provide more information such as editor configuration, or video? Thanks.

**Comment by adrianlee44** [comment]
@geminorum, are you still seeing this bug?

**Comment by geminorum** [comment]
Still a problem on Atom 1.4.1 with aligner 0.18.0 / aligner-php 1.0.0

here I'm using NPP to demonstrate the bug:

![aligner-bug-before](https://cloud.githubusercontent.com/assets/150718/12686182/977db8f6-c6dd-11e5-88a0-f1613e453c31.png)
Before: hence the arrows that represent hard tabs

![aligner-bug-after](https://cloud.githubusercontent.com/assets/150718/12686243/d7a00600-c6dd-11e5-9860-451f382aefaf.png)
After: the replaced dots that represent spaces (soft tabs)

**Comment by adrianlee44** [comment]
I'm using Atom 1.4.1 with the latest aligner and aligner-php on OSX.

I created the file on Atom and double checked on Sublime Text 3. I wasn't able to reproduce the bug but I'll try it again on Windows.

Original file on Atom
<img width="272" alt="screen shot 2016-01-29 at 10 07 30 pm" src="https://cloud.githubusercontent.com/assets/208855/12694083/e465c1e8-c6d5-11e5-8143-7698e0bb1a04.png">
Original file on Sublime
<img width="244" alt="screen shot 2016-01-29 at 10 08 09 pm" src="https://cloud.githubusercontent.com/assets/208855/12694086/e4674482-c6d5-11e5-874e-74eee9bd497b.png">

After aligning on Atom
<img width="225" alt="screen shot 2016-01-29 at 10 09 28 pm" src="https://cloud.githubusercontent.com/assets/208855/12694084/e4671336-c6d5-11e5-8b93-74d2d7329dfe.png">
After aligning on Sublime
<img width="244" alt="screen shot 2016-01-29 at 10 09 36 pm" src="https://cloud.githubusercontent.com/assets/208855/12694085/e467314a-c6d5-11e5-96e7-538ae790e10d.png">

**Comment by adrianlee44** [comment]
I just tried this out on Windows with Atom 1.4.1 and the latest aligner and aligner-php.

This is using Atom and double checking with NPP. I wasn't able to reproduce the bug.

Before
![screenshot1](https://cloud.githubusercontent.com/assets/208855/12694295/1f66db1c-c6de-11e5-80f0-6abc7a5a87bf.PNG)

After
![screenshot2](https://cloud.githubusercontent.com/assets/208855/12694294/1f656c5a-c6de-11e5-87ca-5344fbbb00b4.PNG)

**Comment by geminorum** [comment]
Just tested with freshly installed Atom on Ubuntu, still the same problem. :)

**Comment by adrianlee44** [comment]
I just reproduced the bug. The key was to hide invisibles. Thanks.

**Comment by adrianlee44** [comment]
This should be fixed with v0.18.1. Please let me know if you are still seeing the bug after updating. Thanks for all your help and reporting this issue.

**Comment by geminorum** [comment]
fixed on 1.18.1
thanks a lot.
