### ISSUE TITLE
CSS/LESS selector with double-colon...

### ISSUE THREAD

**Issue by emveeoh** [adrianlee44/atom-aligner#50]
Selectors that require two colons (see example below) are improperly split apart. The second colon is incorrectly aligned with the rest of the css properties. The extra whitespace will break the LESS compiler. Specifically, this happens in LESS documents (.less).   Thank you! :)

For example:
----------------------------------------------------------
atom-text-editor::shadow .cursor {
}

Becomes this after applying Aligner:
----------------------------------------------------------
atom-text-editor:      (((((unintended blank white space here)))))      :shadow .cursor {
}

**Comment by adrianlee44** [comment]
Thanks for reporting this. Let me take a look.

**Comment by adrianlee44** [comment]
It seems like [language-less](https://github.com/atom/language-less) doesn't support `::shadow` properly. I'm going submit a PR to look into fixing it.

**Comment by adrianlee44** [comment]
Opened atom/language-less#55 which should fix this issue.

**Comment by adrianlee44** [comment]
The PR has been merged and the language package has been bumped. This should be fixe in the next release of Atom.
