### ISSUE TITLE
Support for key => value pairs

### ISSUE THREAD

**Issue by raymondbadoux** [adrianlee44/atom-aligner#51]
Hey man, I love this aligner package you built! I especially like the fact that CTRL+Z actually undoes the entire alignment action, instead of un-aligning everything one line at a time and / or freezing the file temporarily (like some of the other alignment packages I tested, did).

Anyway, quick question / suggestion: somehow I'm unable to align key => value pairs in PHP arrays. I tried selecting the array as a whole as well as selecting the key => value pairs only before hitting CTRL+ALT+/, but nothing seemed to work. I have Atom running on both Windows and Linux - same issue on both platforms. Aligning CSS declarations and PHP variables is no problem.

Is there a setting I missed? Am I doing something wrong?

Looking forward to hearing from you. And again, great work! :-)

Raymond
The Netherlands

**Comment by adrianlee44** [comment]
Have you installed [aligner-php package](https://atom.io/packages/aligner-php)?

**Comment by raymondbadoux** [comment]
Hey, thanks your your quick reply! I just installed the PHP specific package and it did the trick - awesome!

**Comment by adrianlee44** [comment]
Glad to hear that it worked out.
