### ISSUE TITLE
Support for PHP associative array key => value

### ISSUE THREAD

**Issue by dylanjameswagner** [adrianlee44/atom-aligner#52]
Trying to align on => has no result.

desired outcome:
```
array(
    1     => 'a',
    '1'   => 'b',
    1.5   => 'c',
    'foo' => 'd',
);
```

**Comment by adrianlee44** [comment]
Have you installed [aligner-php package](https://atom.io/packages/aligner-php)?

**Comment by dylanjameswagner** [comment]
Apologies, I misread the documentation and thought that PHP support was included in the primary package. I have installed aligner-php and all is good. Thank you.
