### ISSUE TITLE
Can't get it to work with LiveScript

### ISSUE THREAD

**Issue by Industrial** [adrianlee44/atom-aligner#53]
Hi!

I'm mainly coding in [LiveScript](http://livescript.net) these days and I have one problem:

Alignment of `{ x, y } = z` does not work.

```
gulp-plumber     = require \gulp-plumber
gulp-spawn-mocha = require \gulp-spawn-mocha
handle-error     = require \../lib/handle-error
{ some, things, here } = require \thing
```

**Comment by adrianlee44** [comment]
Do you use any additional language package for LiveScript?

**Comment by Industrial** [comment]
Yes, I use https://atom.io/packages/language-livescript

**Comment by adrianlee44** [comment]
For clarification, you are looking for the `=` in `{ x, y } = z` to align with previous `=`s, right?

**Comment by Industrial** [comment]
Yes, that would be great :-)

**Comment by adrianlee44** [comment]
The issue is with the grammar. Currently the grammar is parsing `} =` as one token instead of 2. I'll look into creating a PR for that grammar.

**Comment by adrianlee44** [comment]
It also seems like the package is not maintained for a while now so creating a PR might not fix this issue.

**Comment by Industrial** [comment]
Okay, I will look into continuing/owning that package this weekend :-)

**Comment by adrianlee44** [comment]
Let me know if you do as I have a quick patch for the grammar.

I'm going to close this for now.
