### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by bigdogmat** [adrianlee44/atom-aligner#57]
Would be nice to see [Lua ](http://www.lua.org/)support for this.

**Comment by adrianlee44** [comment]
Can you give some examples of what you are trying to align?

**Comment by bigdogmat** [comment]
```lua
local string_format = string.format
local chat_AddText = chat.AddText
local unpack = unpack
local MsgN = MsgN
```
To
```lua
local string_format = string.format
local chat_AddText  = chat.AddText
local unpack        = unpack
local MsgN          = MsgN
```
And possibly table alignment, e.g.
```lua
local tab = {
  stuff = true,
  otherstuff = false,
  morestuff = function()

  end,
}
```
To
```lua
local tab = {
  stuff      = true,
  otherstuff = false,
  morestuff  = function()

  end,
}
```

**Comment by adrianlee44** [comment]
Sorry for the late response. Are you using this package (https://atom.io/packages/language-lua) for grammar support?

**Comment by adrianlee44** [comment]
I just published https://atom.io/packages/aligner-lua which should provide support for Lua. Let me know if you encounter any issue.
