### ISSUE TITLE
Feature Request: Align Javascript new `import ... from ...` syntax 

### ISSUE THREAD

**Issue by EdStudio** [adrianlee44/atom-aligner#58]
First of all, thanks for this great package!

As my usual practice, I would also align the new `import ... from ...` syntax.
Here is an example:
```javascript
import React, { Component } from 'react';
import App                  from 'app/containers/App';
import * as userActions     from 'app/actions/users';
```
I am not so sure if this is easily achievable.
But it would be great if the package could support this either.

Or if you could point out where I should start with, I am willing to have a try on this. 👍 
Thank you!

**Comment by adrianlee44** [comment]
Are you using the JS language pack from Atom or a 3rd party one?

**Comment by pahomov** [comment]
i've tried every language-javascript package, imports didn`t aligned

**Comment by adrianlee44** [comment]
I have published an add-on package for Javascript that better support new syntax.

You can find the package here, https://github.com/adrianlee44/atom-aligner-javascript or search for `aligner-javascript` on Atom
