### ISSUE TITLE
aligning selection tabs contents to the right

### ISSUE THREAD

**Issue by teaman** [adrianlee44/atom-aligner#60]
I select lines of code and press the cmd-cntrl-/ and not only does the alignment behave as described by the Settings, but it also tabs the contents to the right by at least a couple spaces. Not sure why this is being done and why it isn't a Setting that can be disabled.

**Comment by adrianlee44** [comment]
Can you provide an example or record a gif of what you described over? Thanks.

**Comment by teaman** [comment]
Here's a screencast recording.
http://screencast.com/t/4783UrkSVtG

**Comment by adrianlee44** [comment]
This is definitely a bug based on the screencast. Let me take a look at this.

**Comment by adrianlee44** [comment]
Just testing the same code with the latest version of Aligner and it's working properly.

Closing this issue and please let me know if it's still an issue.
