### ISSUE TITLE
TextEditor.module.exports.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by LeslieCarr** [adrianlee44/atom-aligner#61]
Hello - I'm using Atom 1.9.1 and have gotten this below error while using aligner.  I double checked that I'm using the latest aligner package (0.22.0) 

Thanks! 

`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.module.exports.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:87:14)
getTokenizedLineForBufferRow (/Users/lesliecarr/.atom/packages/aligner/lib/helper.js:294:16)
Object.getAlignCharacter (/Users/lesliecarr/.atom/packages/aligner/lib/helper.js:45:19)
Aligner.alignAtRow (/Users/lesliecarr/.atom/packages/aligner/lib/main.js:43:30)
editor.getSelectedBufferRanges.forEach (/Users/lesliecarr/.atom/packages/aligner/lib/main.js:31:14)
Array.forEach (native)
```

**Comment by adrianlee44** [comment]
Thanks for the PR. The fix should be in `v0.22.1`. Please let me know if you are still seeing the issue after updating.
