### ISSUE TITLE
Comment duplication when aligning variables with and without operators.

### ISSUE THREAD

**Issue by mihadis** [adrianlee44/atom-aligner#62]
```
var score = 75;                      // score
var msg;            // message
```

Aligning the above ⬆️ (variables with operators + variables with no operators) results in comment duplication: ⬇️ 

```
var score = 75;                      // score
var msg;            // message       // message
```

The comments are now aligned, but the line with no operator does not delete the comment from the old position. 😩

**Comment by adrianlee44** [comment]
Thanks for reporting this. Taking a look
