### ISSUE TITLE
Align RSpec to eq

### ISSUE THREAD

**Issue by wbotelhos** [adrianlee44/atom-aligner#64]
I could not align the eq values like I was doing on https://github.com/jarod2d/sublime_valign
Is it possible?

From:

```
expect(user.name).to eq 'John Doe',
expect(user.email).to eq 'johndoe@example.org',
```

To:

```
expect(user.name).to  eq 'John Doe',
expect(user.email).to eq 'johndoe@example.org',
```

**Comment by adrianlee44** [comment]
Do you use a language pack for RSpec? If so, can you link it here.

**Comment by wbotelhos** [comment]
I don't, just your plugin.

**Comment by adrianlee44** [comment]
Oh sorry. I meant do you use any other packages for syntax highlighting when editing RSpec files.

**Comment by wbotelhos** [comment]
No, I don't.

It should be working?

**Comment by adrianlee44** [comment]
Not sure if you are still using aligner since it has been a while. Aligner relies on language packages to tokenize text so it can align the correct tokens. Without a rspec language package, Aligner will not work properly.

Going to close this for now. Please let me know if this is still an issue.

**Comment by wbotelhos** [comment]
Hi,

What package do I need plus this one?

Maybe it?: https://atom.io/packages/language-rspec (still not working)

Just now I'm talking about align `eq`, not `:`, `=` etc...

```ruby
expect(1).to eq 1
expect(2).to      eq 2
```

to

```ruby
expect(1).to eq 1
expect(2).to eq 2
```

Thanks.

**Comment by adrianlee44** [comment]
It looks like language-rspec doesn't tokenize/highlight `eq` at the moment. I have submitted a PR to do so. If that PR is accepted, I'll be able to add support for `eq` through `aligner-ruby`, https://atom.io/packages/aligner-ruby

**Comment by adrianlee44** [comment]
Updating aligner-ruby to v1.6.0 and language-rspec to the latest version should align `eq` properly now.

**Comment by wbotelhos** [comment]
Hi @adrianlee44 ,

First, thank you for you job.

I think I'm doing something wrong, because it still does not works for me:

```ruby
expect(1).to eq 1
expect(2).to      eq 2
```
Maybe it is my setup?

![screen shot 2017-05-18 at 2 05 57 pm](https://cloud.githubusercontent.com/assets/116234/26214546/26bd3b34-3bd3-11e7-84f3-2d345fbe4c22.png)
![screen shot 2017-05-18 at 2 05 45 pm](https://cloud.githubusercontent.com/assets/116234/26214548/26d6ffc4-3bd3-11e7-8896-f438d3d4e2c0.png)
![screen shot 2017-05-18 at 2 05 38 pm](https://cloud.githubusercontent.com/assets/116234/26214547/26c02ccc-3bd3-11e7-84f7-426fa2fcafb5.png)

Sorry about that.
And thank you again.

**Comment by wbotelhos** [comment]
You are awesome!

It was `Ruby on Rails`, my bad @adrianlee44 .

Thank you very much! <3
