### ISSUE TITLE
Bug: Removing code (!)

### ISSUE THREAD

**Issue by tomkiss** [adrianlee44/atom-aligner#66]
When aligning this section of react javascript:
```
              {
                navItem:  false,
              },
              // events
              {
                onClick: this.props.onClick,
              },
```
The on click value is removed.

Doesn't fill me with confidence when aligning large blocks of text 🤔

**Comment by adrianlee44** [comment]
Thanks for reporting! Let me take a look.

What language pack are you using?

**Comment by mm-tom** [comment]
Just the base atom-aligner (I have installed but disabled the aligner-javascript and aligner-scss to narrow down the issue).

**Comment by tomkiss** [comment]
Just the base atom-aligner (I have installed but disabled the aligner-javascript and aligner-scss to narrow down the issue).

**Comment by adrianlee44** [comment]
I'm trying to reproduce the issue right now but having trouble doing so.

atom-aligner requires on other language package to parse your code. Did you install additional packages for syntax highlighting for react, such as https://atom.io/packages/react?

What block have you selected or where was your cursor when you try to align the block above?

Any chance you can paste a larger code block?

Thanks!

**Comment by tomkiss** [comment]
Heya,
No additional packages parsing the code, afaik. This occurs when type is set to "Javascript with JSX". I can repro with just the text above pasted in new file with type set to Javascript with JSX.

**Comment by adrianlee44** [comment]
Not sure if you are still using Aligner but are you still experiencing the issue with the latest version (v1.2.1)?

**Comment by tomkiss** [comment]
Hi there, just tried this and it appears to be fixed now :)

Thanks!

**Comment by adrianlee44** [comment]
Glad to hear that the issue is resolved.
