### ISSUE TITLE
Aligner not working on Linux

### ISSUE THREAD

**Issue by nubilfi** [adrianlee44/atom-aligner#67]
Hi, 
I'm using linux 64bit (Debian 8) but it seems the aligner not working at all. I've even tried to change the keymap shortcut but its still not working.

**Comment by adrianlee44** [comment]
Which language are you trying to align? Aligner used to have a basic set of config but that has since been removed in 1.0.0

**Comment by nubilfi** [comment]
Javascript. I've installed [aligner-javascript](https://atom.io/packages/aligner-javascript), and also restart the atom for several times, but still not working. I'll try to restart my laptop now and hope it'll work

**Comment by adrianlee44** [comment]
What's the file extension of your JS file? Did you install any other JavaScript language pack?

**Comment by nubilfi** [comment]
`.js` files. But it's already working now, i'm not quite sure, after restart my laptop the aligner working fine
