### ISSUE TITLE
Bug? All my spaces are replaced with "·"

### ISSUE THREAD

**Issue by mpolichette** [adrianlee44/atom-aligner#7]
I'm not sure what has happened, when I first got this plugin it was working amazingly.... so :+1:  for that!   However, for some reason it started also replacing all the spaces on the lines it aligned with "·" ([Middle Dots](http://www.fileformat.info/info/unicode/char/00b7/index.htm)).

I'm wondering if anyone has seen this before.

Anyway, I haven't dug in to find out why, but it is preventing me from using the plugin for now.  If I find some time in the future I'll see if I can debug it more.

Thanks!

**Comment by dcalhoun** [comment]
@adrianlee44 I'm experiencing this issue as well inside of a JavaScript file. My soft tab spaces are replaced with a `·` character. Does atom-aligner take into account whether the user utilizes soft tabs? [Here's a short screencast of the issue](http://quick.as/b7wyfrolo).

![atom-aligner spaces](https://cloud.githubusercontent.com/assets/438664/6924068/71028d32-d79b-11e4-8d57-7e5f67bc95a2.gif)

#### Environment:
- atom-aligner v0.9.1
- atom 0.188.0
- Mac OS X 10.10.2

**Comment by adrianlee44** [comment]
hi @dcalhoun, thanks for reporting this issue. This is a known bug on my end but I haven't created an issue yet on Github yet.

The problem is `invisibles` are getting converted into real text. Disabling invisible will fix the problem for now but I'm looking into this issue.

**Comment by adrianlee44** [comment]
I have made a new issue, #17 to better track this bug.
