### ISSUE TITLE
where to modify alignment options ?

### ISSUE THREAD

**Issue by levblanc** [adrianlee44/atom-aligner#70]
Hi,

I went through the custom config guidelines in [this wiki page](https://github.com/adrianlee44/atom-aligner/wiki/User-configurations),
but didn't figure out how to make those changes.

Anyone please help.

**Comment by adrianlee44** [comment]
Hi @levblanc, aligner is a barebone package. The configurations are in the addon packages. What language are you trying to align?

**Comment by levblanc** [comment]
Hi @adrianlee44,

Thanks for letting me know. 
I was looking for settings in the aligner package itself for some time.
Would be better if you could add a note in the wiki page.  :)

**Comment by adrianlee44** [comment]
Thanks for the suggestion. The wiki pages are definitely out of date and should be updated.
