### ISSUE TITLE
different from file vue and file js

### ISSUE THREAD

**Issue by semi-xi** [adrianlee44/atom-aligner#72]
a.vue
```vue
<template lang="html">
  <div class="">
      
  </div>
</template>

<script>
export default {
    data ()[
        return {
            a:  1,
            b    :2,
        }
    ]
}
</script>

<style lang="css">
</style>
```
when i select the text 
```
{
     a :  1,
     b     :2,
}
```
and run the plugin ,it can't be what i want
```
{
        a : 1,
        b : 2
}
```
but if the same `json`in file js
it can what i want.
```js
//a.js
var c = {
    a         : 1,
    b :     2    
}
```

**Comment by semi-xi** [comment]
i remember the previous version is ok ,but ,when i update it's not work as i want

**Comment by adrianlee44** [comment]
The updated version of aligner doesn't come with any language support. It seems like you have downloaded `atom-aligner-javascript`? Which language package are you using for Vue syntax highlight?

**Comment by semi-xi** [comment]
@adrianlee44  
i use `language-vue`、`vue-autocompile`and`vue2-autocomplete`.
i check all my atom package and uninstall all the aligner package which name  is indexOf 'aligner' .

after  that i install `atom-aligner`,it let me install the dependent package [aligner-javascript](https://atom.io/packages/aligner-javascript)

**Comment by adrianlee44** [comment]
Did downloading the latest version (v1.2.0) of aligner-javascript fix the issue for you?

**Comment by semi-xi** [comment]
@adrianlee44 the same as before, no working.
Finally, no way, I decided to manually align -)

**Comment by adrianlee44** [comment]
Hm... I just installed language-vue with the code sample you provided above and i was able to align

```
<script>
export default {
    data ()[
        return {
            a:  1,
            b    :2,
        }
    ]
}
</script>
```

to 

```
<script>
export default {
    data ()[
        return {
            a: 1,
            b: 2,
        }
    ]
}
</script>
```

If you do `apm list --packages`, what shows up under "Community Packages"?

**Comment by semi-xi** [comment]
@adrianlee44 ORZ, it seems work,but i don't konw what happen.
maybe some plugins conflict . i have no idea.
but the result looks good :)

**Comment by adrianlee44** [comment]
:) Good to hear! Going to close this for now. Let me know if you are still experiencing issues.
