### ISSUE TITLE
Atom aligner not working

### ISSUE THREAD

**Issue by kondalraodurgam** [adrianlee44/atom-aligner#73]
I installed atom aligner but its not working in in my atom

**Comment by adrianlee44** [comment]
Hi @kondalraodurgam, what languages are you trying to align. Aligner doesn't come with language support.

If you are looking for Javascript support, you can download this package, https://atom.io/packages/aligner-javascript

**Comment by kondalraodurgam** [comment]
Hi@adrianlee44 , iam using javascript purpose but its alignment doesn't work

**Comment by adrianlee44** [comment]
Hm... can you run `apm ls` and provide the list of packages under `Community Packages`? Thanks.

**Comment by m-pokrovskii** [comment]
is Packages -> Aligner -> Align works?

**Comment by adrianlee44** [comment]
@m-pokrovskii, using the menu should work as long as there is a cursor on the editor before clicking the menu

**Comment by tomkiss** [comment]
This has not been working for me for a while now also.

Here's my community packages list:

```├── aligner@1.2.4
├── aligner-javascript@1.3.0
├── atom-beautify@0.30.5
├── atom-ternjs@0.18.3
├── auto-detect-indentation@1.3.0
├── autoclose-html@0.23.0
├── busy-signal@1.4.3
├── craft-twig@0.4.0
├── docblockr@0.11.0
├── git-plus@7.9.3
├── git-time-machine@1.5.9
├── goto-definition@1.3.4
├── highlight-selected@0.13.1
├── increment-me@0.4.1
├── intentions@1.1.5
├── language-javascript-jsx@0.3.7
├── linter@2.2.0
├── linter-csslint@1.3.4
├── linter-htmlhint@1.3.3
├── linter-jshint@3.1.5
├── linter-ui-default@1.6.4
├── minimap@4.29.6
├── oceanic-next@1.0.0
├── pigments@0.39.1
├── react@0.16.2
└── todo-show@1.11.0
```

**Comment by adrianlee44** [comment]
@tomkiss, it seems like the core package `aligner` is missing in your community packages list.

**Comment by mm-tom** [comment]
Yes, sorry for some reason that was truncated. It's the first item on the list.
```├── aligner@1.2.4
```

**Comment by adrianlee44** [comment]
Can you share some of the code snippet you are trying to align?

**Comment by mm-tom** [comment]
I've been just testing it on the example given in the README.

```let random = {
  troll: "internet",
  foo: "bar",
  bar: "beer"
}```

**Comment by adrianlee44** [comment]
I'm having trouble reproducing the issue. Please make sure there is no keybinding conflict with aligner. I'm going to close this issue and open a new issue if it's still a problem.
