### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by marcghorayeb** [adrianlee44/atom-aligner#74]
Hello,
First of all, great work on the module! Really useful for any maniacs like myself ;)
I was wondering how ward would it be to make the atom-aligner-javascript package to support typescript files? Has this been already tested or not?
Best regards,
Marc

**Comment by adrianlee44** [comment]
There hasn't been a need for TypeScript support so I haven't looked into it yet. You can also create an TypeScript aligner addon package by copying most of atom-aligner-javascript code.

You would need to update the selector to `.source.ts` and `.source.tsx`. Also update the the scope of the character you are trying to align.

**Comment by marcghorayeb** [comment]
Okay, I'll try to look into it, will let you know how it goes 👍

**Comment by marcghorayeb** [comment]
Created the package here : https://github.com/marcghorayeb/atom-aligner-typescript
Quickly tested, seems to work, great work on the main plugin, thanks for the help :)
