### ISSUE TITLE
Aligner stopped working after atom updated to 1.19.0

### ISSUE THREAD

**Issue by funbers** [adrianlee44/atom-aligner#75]
I've confirmed no keyboard collisions. Also selected command from menu.

Before update it aligned things perfectly in my lua and js files. After update it does nothing.

Version of aligner: 1.2.4, aligner-javascript: 1.3.0

**Comment by adrianlee44** [comment]
Aligner-javascript should support js files. What are you trying to align and can you share some sample snippets?

As for lua, you would have to download `aligner-lua`.

**Comment by adrianlee44** [comment]
Is this still an issue? Closing this for now. Please reopen and update this issues if this is still a problem.
